/*
 * generated by Xtext 2.37.0
 */
package tools.vitruv.dsls.reactions.ide

import org.eclipse.xtext.validation.IResourceValidator
import tools.vitruv.dsls.reactions.ide.AbstractReactionsLanguageIdeModule

/**
 * Use this class to register ide components.
 */
class ReactionsLanguageIdeModule extends AbstractReactionsLanguageIdeModule {
	/**
	 * Binds the resource validator the editor uses.
	 *
	 * @return the validator that keeps the editor from validating the whole index
	 */
	def Class<? extends IResourceValidator> bindIResourceValidator() {
		EditorResourceValidator
	}
}
