/*
 * generated by Xtext 2.37.0
 */
package tools.vitruv.dsls.reactions.ide

import org.eclipse.xtext.validation.IResourceValidator
import tools.vitruv.dsls.reactions.ide.AbstractReactionsLanguageIdeModule

/**
 * Use this class to register ide components.
 */
class ReactionsLanguageIdeModule extends AbstractReactionsLanguageIdeModule {
	def Class<? extends IResourceValidator> bindIResourceValidator() {
		EditorResourceValidator
	}
}
